Repository codeit-sprint-FE11-part4-8team/coworkers, pull requests merged in 2025-02, with the labels that each got.

#75 팀 소속 없는 경우 퍼블리싱
  public/contents/img_team_empty_desktop.png
  src/app/(routes)/invitation/page.tsx
  src/app/(routes)/noteam/page.tsx
Labels: ✨ 신규 기능, 💄 스타일

#78 Header 부분 로그인후 보이는 프로필이미지, 드랍다운 구현완료
  src/app/components/common/header/Header.tsx
  src/app/hooks/useDropdown.ts
Labels: ✨ 신규 기능, 💬 논의 필요

#76 팀 페이지 리포트 추가
  package-lock.json
  package.json
  public/contents/img_team_empty_desktop.png
  src/app/(routes)/[teamid]/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/(routes)/noteam/page.tsx
  src/app/components/icons/IconReportDone.tsx
  src/app/components/icons/IconReportTodo.tsx
  src/app/components/team/ProgressChart.tsx
  src/app/components/team/Report.tsx
  src/app/components/team/TaskSummaryCard.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TodoList.tsx
  src/app/components/team/TodoListItem.tsx
  src/app/lib/group/getGroup.ts
  src/app/lib/instance.ts
  src/app/types/grouptask.ts
  src/app/utils/getTodayDate.ts
  src/app/utils/groupTaskReport.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API

#80 팀 추가 로그인 분기처리 추가
  src/app/(routes)/addteam/page.tsx
  src/app/lib/group/postGroup.ts
  src/app/lib/image/postImage.ts
  src/app/lib/instance.ts
Labels: 💫 업데이트, 📡 API, ♻️ 리팩토링

#82 fix: formatDate 버셀오류 수정
  src/app/(routes)/boards/[boardid]/page.tsx
  src/app/components/myhistory/HistoryList.tsx
Labels: 🐛 버그

#84 팀 참여하기 로그인 분기 처리 추가
  src/app/(routes)/addteam/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/common/header/Header.tsx
  src/app/hooks/useRedirectLogin.ts
  src/app/lib/group/deleteMemeber.ts
  src/app/lib/group/postAcceptInvitation.ts
Labels: 💫 업데이트, 💬 논의 필요, 📡 API, ♻️ 리팩토링, 🔄 커스텀 훅

#83 팀 수정 로그인 분기 처리 추가 및 refresh-token 로직 수정
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/components/team/DropdownMenu.tsx
  src/app/components/team/ProfileUploader.tsx
  src/app/components/team/TeamForm.tsx
  src/app/lib/auth/postRefreshApi.ts
  src/app/lib/instance.ts
  src/app/lib/tokenInterceptor.ts
  src/app/utils/handleTokenRefresh.ts
Labels: 💫 업데이트, 📡 API, ♻️ 리팩토링

#85 자유게시판 상세페이지 댓글 관련기능 구현
  package-lock.json
  src/app/(routes)/boards/.gitkeep
  src/app/(routes)/boards/[boardid]/page.tsx
  src/app/components/boarddetail/AddComment.tsx
  src/app/components/boarddetail/CommentDropdown.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/icons/IconHeart.tsx
  src/app/components/icons/IconMore.tsx
  src/app/components/myhistory/HistoryList.tsx
  src/app/lib/article/getArticleDetail.ts
  src/app/lib/articlecomment/deleteArticleComment.ts
  src/app/lib/articlecomment/getArticleComment.ts
  src/app/lib/articlecomment/patchArticleComment.ts
  src/app/lib/articlecomment/postArticleComment.ts
Labels: ✨ 신규 기능, 💬 논의 필요, 📁 컴포넌트, 📡 API

#86 팀 페이지 할 일 목록 생성/수정/삭제 기능 추가
  src/app/components/common/input/Input.tsx
  src/app/components/team/HeaderDropdown.tsx
  src/app/components/team/Report.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TodoList.tsx
  src/app/components/team/TodoListItem.tsx
  src/app/utils/getTodayDate.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API

#87 할 일 상세 수정/댓글 기능 구현 완료
  package.json
  src/app/components/common/dropdown/DropdownItem.tsx
  src/app/components/taskdetail/DeleteCommentModal.tsx
  src/app/components/taskdetail/TaskComment.tsx
  src/app/components/taskdetail/TaskCommentCard.tsx
  src/app/components/taskdetail/TaskCommentDropdown.tsx
  src/app/components/taskdetail/TaskCommentInput.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/lib/comment/deleteComment.ts
  src/app/lib/comment/getComment.ts
  src/app/lib/comment/patchComment.ts
  src/app/lib/comment/postComment.ts
  src/app/utils/formatTime.ts
Labels: ✨ 신규 기능, 📁 컴포넌트

#89 자유게시판 상세페이지 수정 구현
  src/app/(routes)/boards/[boardid]/page.tsx
  src/app/components/boarddetail/AddComment.tsx
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/boarddetail/DeleteArticleModal.tsx
  src/app/components/icons/IconMember.tsx
  src/app/lib/article/deleteArticle.ts
  src/app/lib/article/patchArticle.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API

#91 리스트 페이지 API 연동
  package-lock.json
  src/app/(routes)/[teamid]/[tasklist]/[taskid]/page.tsx
  src/app/(routes)/[teamid]/[tasklist]/page.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/taskdetail/TaskDetailDropdown.tsx
  src/app/components/tasklist/CreateTaskModal.tsx
  src/app/components/tasklist/DeleteRecurringModal.tsx
  src/app/components/tasklist/DeleteTaskModal.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/tasklist/TaskCardDropdown.tsx
  src/app/components/tasklist/TaskCardList.tsx
  src/app/components/team/TodoListItem.tsx
  src/app/lib/group/getGroupById.ts
Labels: 💫 업데이트, 💬 논의 필요, 📝 문서, 📡 API, ♻️ 리팩토링

#90 그룹 삭제 및 팀 페이지 타입 에러 수정
  package-lock.json
  src/app/(routes)/[teamid]/page.tsx
  src/app/components/team/HeaderDropdown.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TodoList.tsx
  src/app/components/team/TodoListItem.tsx
  src/app/lib/group/deleteGroup.ts
Labels: ✨ 신규 기능, 🐛 버그, 📁 컴포넌트, 📡 API

#94 멤버 & 팀 관련 리뷰 반영
  src/app/(routes)/invitation/page.tsx
  src/app/components/common/modal/ConfirmModal.tsx
  src/app/components/common/modal/Modal.tsx
  src/app/components/team/AddMemberModal.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/MemberContainer.tsx
Labels: 💫 업데이트, 📁 컴포넌트, ♻️ 리팩토링

#93 팀 페이지 타입 에러 수정
  src/app/components/team/HeaderDropdown.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TodoList.tsx
Labels: 🐛 버그

#95 팀 페이지 queryKey추가
  src/app/components/team/TaskListDropdown.tsx
Labels: 🐛 버그

#96 할 일 목록 추가 및 목록 리스트 UI 구현
  src/app/(routes)/[teamid]/[tasklist]/[taskid]/page.tsx
  src/app/(routes)/[teamid]/[tasklist]/page.tsx
  src/app/components/taskdetail/TaskCommentCard.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/tasklist/CreateListModal.tsx
  src/app/components/tasklist/DatePicker.tsx
  src/app/lib/tasklist/postTaskList.ts
  src/app/utils/formatTime.ts
Labels: 📁 컴포넌트, 📡 API, ♻️ 리팩토링

#98 mypage 이미지 업로드 및 닉네임 변경 구현
  src/app/(routes)/addboard/page.tsx
  src/app/(routes)/boards/[boardid]/editboard/page.tsx
  src/app/(routes)/mypage/page.tsx
  src/app/components/boarddetail/CommentDropdown.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/boarddetail/DeleteCommentModal.tsx
  src/app/components/mypage/DeleteAccount.tsx
  src/app/components/mypage/NicknameChanger.tsx
  src/app/components/mypage/ProflieChanger.tsx
  src/app/components/mypage/ResetPassword.tsx
  src/app/components/mypage/ResetPasswordModal.tsx
  src/app/lib/user/patchUser.ts
Labels: ✨ 신규 기능, 💫 업데이트, 📁 컴포넌트, 📡 API

#99 할 일 추가 모달에서 중복 요청 방지
  src/app/components/tasklist/CreateTaskModal.tsx
Labels: 🐛 버그, ♻️ 리팩토링

#102 로그인 상태에 따른 페이지 이동 경로 변경 및 메인 페이지 스크롤시 애니메이션 추가
  package-lock.json
  package.json
  src/app/components/landing/LandingFeatures.tsx
  src/app/components/landing/LandingFooter.tsx
  src/app/components/landing/LandingHeader.tsx
  src/app/lib/user/getUser.ts
Labels: ✨ 신규 기능, 📁 컴포넌트

#103 팀 리스트 페이지 할 일 카드 Drag&Drop 구현
  package-lock.json
  package.json
  src/app/components/taskdetail/TaskCommentCard.tsx
  src/app/components/tasklist/SortableTaskCard.tsx
  src/app/components/tasklist/TaskCardList.tsx
  src/app/lib/task/patchTask.ts
Labels: ✨ 신규 기능, 💄 스타일, 📁 컴포넌트, 📡 API, 📦 패키지

#104 수정하기 버그 수정 및 이미지 업로드 확인 모달 추가
  src/app/(routes)/boards/[boardid]/editboard/page.tsx
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/editboard/ArticleChanger.tsx
  src/app/components/editboard/ImageChanger.tsx
  src/app/components/mypage/ProflieChanger.tsx
  src/app/lib/article/patchArticle.ts
  src/app/lib/image/postImage.ts
Labels: ✨ 신규 기능, 🐛 버그, 💫 업데이트

#100 팀 생성, 수정 API 요청 중복 방지
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/(routes)/addteam/page.tsx
  src/app/components/team/TeamForm.tsx
Labels: 💫 업데이트, ♻️ 리팩토링

#108 할 일 리스트/할 일 상세 페이지 오류 및 스타일 수정
  src/app/(routes)/[teamid]/[tasklist]/page.tsx
  src/app/components/taskdetail/TaskCommentCard.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/taskdetail/TaskDetailDropdown.tsx
  src/app/components/tasklist/CreateListModal.tsx
  src/app/components/tasklist/CreateTaskModal.tsx
  src/app/components/tasklist/DeleteRecurringModal.tsx
  src/app/components/tasklist/DeleteTaskModal.tsx
  src/app/components/tasklist/EditTaskModal.tsx
  src/app/components/tasklist/TaskCardDropdown.tsx
Labels: 🐛 버그, ♻️ 리팩토링

#105 팀, 멤버 관련 기능 리팩토링 및 UX 개선
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/(routes)/[teamid]/page.tsx
  src/app/(routes)/addteam/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/common/auth/AuthCheckLoading.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/MemberContainer.tsx
  src/app/hooks/useAuthRedirect.ts
  src/app/hooks/useRedirectLogin.ts
  src/app/utils/uploadImage.ts
Labels: 💫 업데이트, 📁 컴포넌트, ♻️ 리팩토링, 🔄 커스텀 훅, 🔨유틸리티

#106 공통 모달 닫기(x) 버튼 Default로 수정
  src/app/components/common/modal/Modal.tsx
Labels: 💫 업데이트, 📁 컴포넌트

#110 자유 게시판 관련 부분 수정완료, 스켈레톤 추가완료
  src/app/(routes)/boards/page.tsx
  src/app/components/boards/BoardsSearchBar.tsx
  src/app/components/boards/BoardsSkeleton.tsx
  src/app/components/boards/CommonAriticleCard.tsx
  src/app/hooks/useArticleActions.ts
  src/app/styles/globals.css
  tailwind.config.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, ♻️ 리팩토링

#111 할 일 리스트/상세 유효성 검사 추가 및 스타일 수정
  src/app/components/common/modal/Modal.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/tasklist/CreateTaskModal.tsx
  src/app/components/tasklist/CustomCalendar.tsx
  src/app/components/tasklist/DateTimeSeletor.tsx
  src/app/components/tasklist/DeleteRecurringModal.tsx
  src/app/components/tasklist/DeleteTaskModal.tsx
  src/app/components/tasklist/EditTaskModal.tsx
  src/app/components/tasklist/RepeatSelector.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/styles/calendar.css
Labels: 🐛 버그, 💄 스타일, 💫 업데이트, ♻️ 리팩토링

#114 자유게시판 이슈 해결완료
  src/app/(routes)/boards/page.tsx
  src/app/components/boards/BoardsOrderDropDown.tsx
  src/app/components/boards/BoardsSkeleton.tsx
  src/app/components/boards/CommonAriticleCard.tsx
  src/app/components/icons/BoardsLikeIcon.tsx
Labels: ✨ 신규 기능, 🐛 버그, 💄 스타일, ♻️ 리팩토링

#117 자유게시판 수정페이지 이슈 해결
  src/app/components/editboard/ArticleChanger.tsx
Labels: ♻️ 리팩토링

#112 팀 페이지 1차 배포 이슈 해결
  src/app/components/team/ProgressChart.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TodoList.tsx
  src/app/components/team/TodoListItem.tsx
  tailwind.config.ts
Labels: 🐛 버그, 💄 스타일, 📁 컴포넌트

#115 헤더, 사이드바에 그룹 데이터 추가
  src/app/components/common/header/Header.tsx
  src/app/components/common/header/HeaderTeam.tsx
  src/app/components/common/header/SideMenubar.tsx
  src/app/components/common/header/TeamHeaderDropdown.tsx
  src/app/components/common/header/TeamSidebar.tsx
  src/app/components/icons/IconDefaultImage.tsx
  src/app/components/icons/IconHeaderCheck.tsx
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API

#119 할 일 리스트/상세 + 자유게시판 상세(준희님) 1차 배포 이슈 해결
  src/app/(routes)/[teamid]/[tasklist]/page.tsx
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/taskdetail/TaskComment.tsx
  src/app/components/taskdetail/TaskCommentSkeleton.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/taskdetail/TaskDetailSkeleton.tsx
  src/app/components/tasklist/TaskCardList.tsx
  src/app/components/tasklist/TaskCardSkeleton.tsx
  src/app/hooks/useSaveScroll.ts
  src/app/styles/globals.css
  src/app/utils/formatDate.ts
Labels: 🐛 버그, ♻️ 리팩토링, 🔄 커스텀 훅, 🔨유틸리티

#120 로그인/회원가입 구글관련 ui, 로직 제거완료
  src/app/(routes)/auth/callback/google/page.tsx
  src/app/components/auth/callback/GoogleCallback.tsx
  src/app/components/login/LoginForm.tsx
  src/app/components/login/QuickLogin.tsx
  src/app/components/login/ResetPasswordModal.tsx
  src/app/lib/auth/postProviderApi.ts
  src/app/lib/oauth/postOauthApi.ts
Labels: ♻️ 리팩토링

#121 자유게시판 스켈레톤 ui변경, 애니메이션 삭제
  src/app/components/boards/BoardsSkeleton.tsx
  tailwind.config.ts
Labels: ♻️ 리팩토링

#125 자유게시판 상세페이지 이슈 해결
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentList.tsx
Labels: 💫 업데이트, ♻️ 리팩토링

#118 이미지 업로드 및 멤버 관련 이슈 해결
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/(routes)/addteam/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/team/DetailMemberModal.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/MemberCardSkeleton.tsx
  src/app/components/team/MemberContainer.tsx
  src/app/components/team/ProfileUploader.tsx
  src/app/components/team/TeamForm.tsx
  src/app/utils/uploadImage.ts
Labels: 🐛 버그, 💄 스타일, ♻️ 리팩토링

#129 할 일 리스트/상세 컴포넌트 리팩토링 #1
  src/app/(routes)/[teamid]/[tasklist]/page.tsx
  src/app/components/common/modal/ConfirmModal.tsx
  src/app/components/taskdetail/DeleteCommentModal.tsx
  src/app/components/taskdetail/TaskCommentCard.tsx
  src/app/components/taskdetail/TaskCommentDropdown.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/taskdetail/TaskDetailDropdown.tsx
  src/app/components/tasklist/CreateTaskModal.tsx
  src/app/components/tasklist/DatePicker.tsx
  src/app/components/tasklist/DateRepeatInfo.tsx
  src/app/components/tasklist/DateTimeSeletor.tsx
  src/app/components/tasklist/DeleteRecurringModal.tsx
  src/app/components/tasklist/DeleteTaskModal.tsx
  src/app/components/tasklist/EditTaskModal.tsx
  src/app/components/tasklist/SortableTaskCard.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/tasklist/TaskCardDropdown.tsx
  src/app/components/tasklist/TimeSelector.tsx
  src/app/utils/formatDate.ts
  src/app/utils/formatTime.ts
Labels: 🐛 버그, 💄 스타일, 💫 업데이트, ♻️ 리팩토링

#132 자유게시판 상세페이지, 마이페이지 리팩토링
  src/app/(routes)/addboard/page.tsx
  src/app/(routes)/mypage/page.tsx
  src/app/components/boarddetail/AddComment.tsx
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentDropdown.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/boarddetail/DeleteArticleModal.tsx
  src/app/components/boarddetail/DeleteCommentModal.tsx
  src/app/components/editboard/ArticleChanger.tsx
  src/app/components/editboard/ImageChanger.tsx
  src/app/components/myhistory/HistoryList.tsx
  src/app/components/mypage/DeleteAccount.tsx
  src/app/components/mypage/NicknameChanger.tsx
  src/app/components/mypage/ResetPassword.tsx
  src/app/components/mypage/ResetPasswordModal.tsx
Labels: 🐛 버그, 💫 업데이트, ♻️ 리팩토링

#131 팀 페이지 1차 배포 오류 수정 및 Skeleton UI 추가
  src/app/(routes)/[teamid]/page.tsx
  src/app/components/team/HeaderDropdown.tsx
  src/app/components/team/MemberCardSkeleton.tsx
  src/app/components/team/ProgressChart.tsx
  src/app/components/team/Report.tsx
  src/app/components/team/ReportSkeleton.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TeamHeaderSkelton.tsx
  src/app/components/team/TodoList.tsx
  src/app/components/team/TodoListItem.tsx
  src/app/components/team/TodoListSkeleton.tsx
Labels: ✨ 신규 기능, 🐛 버그, 📁 컴포넌트

#135 Header부분 로그아웃하고 바로 다른 계정으로 로그인할때 생기는 이슈 해결완료
  src/app/components/common/header/Header.tsx
Labels: 🐛 버그, ♻️ 리팩토링

#136 자유게시판 : 수정하기 삭제하기 보이는 버튼 아이콘 IconMore->TaskCardDropDown으로 변경완료
  src/app/components/boards/CommonAriticleCard.tsx
Labels: ♻️ 리팩토링

#137 모달 리팩토링
  src/app/components/common/modal/Modal.tsx
  src/app/components/team/MemberContainer.tsx
  src/app/utils/getRandomId.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, ♻️ 리팩토링, 🔨유틸리티

#139 팀 페이지 리팩토링 및 멤버 접근 제한 로직 추가
  public/icons/ic_star.webp
  src/app/(routes)/[teamid]/[tasklist]/page.tsx
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/(routes)/[teamid]/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/MemberContainer.tsx
  src/app/hooks/useRedirectIfNotMember.ts
  src/app/lib/group/getGroupById.ts
Labels: ✨ 신규 기능, 💄 스타일, 💫 업데이트, 📡 API, ♻️ 리팩토링, 🔄 커스텀 훅

#142 alert -> Toast로 변경
  package-lock.json
  package.json
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/(routes)/addboard/page.tsx
  src/app/(routes)/addteam/page.tsx
  src/app/(routes)/boards/[boardid]/editboard/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/auth/callback/KaKaoCallback.tsx
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/DeleteArticleModal.tsx
  src/app/components/editboard/ArticleChanger.tsx
  src/app/components/mypage/DeleteAccount.tsx
  src/app/components/mypage/NicknameChanger.tsx
  src/app/components/mypage/ResetPasswordModal.tsx
  src/app/components/resetpassword/ResetPasswordForm.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TodoList.tsx
  src/app/hooks/useArticleActions.ts
  src/app/hooks/useAuthRedirect.ts
  src/app/hooks/useConfirmPassword.ts
  src/app/hooks/useRedirectIfNotMember.ts
  src/app/hooks/useResetPassword.ts
  src/app/hooks/useSignIn.ts
  src/app/hooks/useSignUp.ts
  src/app/hooks/useToast.ts
  src/app/layout.tsx
Labels: ✨ 신규 기능, ♻️ 리팩토링

#149 공통 컴포넌트 드롭다운 애니메이션 추가
  src/app/components/common/dropdown/Dropdown.tsx
  src/app/components/common/dropdown/DropdownItem.tsx
  src/app/components/common/dropdown/DropdownList.tsx
  src/app/components/common/dropdown/DropdownToggle.tsx
Labels: 💄 스타일, ♻️ 리팩토링

#147 카카오 로그인관련 상태관리값 추가완료
  src/app/components/common/header/Header.tsx
  src/app/components/login/QuickLogin.tsx
  src/app/stores/oauthSlice.ts
  src/app/stores/store.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, ♻️ 리팩토링

#148 로그인 정보 & 접근 권한 로직 충돌 수정
  src/app/(routes)/invitation/page.tsx
  src/app/hooks/useRedirectIfNotMember.ts
Labels: 🐛 버그, 💫 업데이트

#152 할 일 리스트/상세 토스트
  src/app/components/taskdetail/TaskComment.tsx
  src/app/components/taskdetail/TaskCommentCard.tsx
  src/app/components/taskdetail/TaskCommentDropdown.tsx
  src/app/components/taskdetail/TaskCommentInput.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/taskdetail/TaskDetailDrawer.tsx
  src/app/components/tasklist/CreateListModal.tsx
  src/app/components/tasklist/CreateTaskModal.tsx
  src/app/components/tasklist/DeleteRecurringModal.tsx
  src/app/components/tasklist/DeleteTaskModal.tsx
  src/app/components/tasklist/EditTaskModal.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/tasklist/TaskCardList.tsx
Labels: 💄 스타일, ♻️ 리팩토링

#151 사이드 메뉴 열렸을떄 스크롤 막기 닫으면 다시 스크롤 활성화
  src/app/components/common/header/Header.tsx
  src/app/components/common/header/SideMenubar.tsx
Labels: ✨ 신규 기능, ♻️ 리팩토링

#150 Toast message 통일
  src/app/(routes)/[teamid]/edit/page.tsx
  src/app/(routes)/addboard/page.tsx
  src/app/(routes)/addteam/page.tsx
  src/app/(routes)/boards/[boardid]/editboard/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/auth/callback/KaKaoCallback.tsx
  src/app/components/boarddetail/AddComment.tsx
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentList.tsx
  src/app/components/boarddetail/DeleteArticleModal.tsx
  src/app/components/editboard/ArticleChanger.tsx
  src/app/components/mypage/DeleteAccount.tsx
  src/app/components/mypage/NicknameChanger.tsx
  src/app/components/mypage/ResetPasswordModal.tsx
  src/app/components/resetpassword/ResetPasswordForm.tsx
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TodoList.tsx
  src/app/hooks/useArticleActions.ts
  src/app/hooks/useAuthRedirect.ts
  src/app/hooks/useConfirmPassword.ts
  src/app/hooks/useRedirectIfNotMember.ts
  src/app/hooks/useResetPassword.ts
  src/app/hooks/useSignIn.ts
  src/app/hooks/useSignUp.ts
Labels: ♻️ 리팩토링

#153 2차 배포 이슈 해결 & 카카오 로그인 비밀번호 변경 불가 구현
  src/app/components/boarddetail/BoardDetail.tsx
  src/app/components/boarddetail/CommentDropdown.tsx
  src/app/components/myhistory/HistoryList.tsx
  src/app/components/mypage/ResetPassword.tsx
Labels: ✨ 신규 기능, 🐛 버그, ♻️ 리팩토링

#154 할일 목록 리스트 스크롤 추가
  src/app/components/team/TodoList.tsx
  src/app/components/team/TodoListItem.tsx
Labels: ✨ 신규 기능, 💄 스타일, ♻️ 리팩토링

#155 헤더 groupName 너비 고정 및 이미지 추가
  src/app/components/common/header/HeaderTeam.tsx
  src/app/components/common/header/SideMenubar.tsx
  src/app/components/common/header/TeamHeaderDropdown.tsx
Labels: 💄 스타일, 📁 컴포넌트, ♻️ 리팩토링

#156 TodolistItem 드래그 시도시 화면 움직임 없도록 수정
  src/app/components/team/TaskListDropdown.tsx
  src/app/components/team/TodoList.tsx
Labels: 🐛 버그, 📁 컴포넌트

#157 모달 내부 드래그 시 이벤트 버블링 현상 수정
  src/app/components/common/modal/Modal.tsx
Labels: 🐛 버그

#160 teamheader 가운데 정렬 추가
  src/app/components/common/header/TeamHeaderDropdown.tsx
Labels: 💄 스타일, 📁 컴포넌트

#162 할 일 리스트/상세 중복 토스트 삭제
  src/app/components/taskdetail/TaskDetail.tsx
  src/app/components/tasklist/TaskCard.tsx
Labels: 🐛 버그
