Repository codeit-sprint-FE11-part4-8team/coworkers, pull requests merged in 2025-01, with the labels that each got.

#8 #4 이슈 생성 테스트2
  public/contents/.gitkeep
  public/file.svg
  public/globe.svg
  public/icons/.gitkeep
  public/logos/.gitkeep
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/api/.gitkeep
  src/app/components/.gitkeep
  src/app/constants/.gitkeep
  src/app/favicon.ico
  src/app/hooks/.gitkeep
  src/app/routes/addteam/.gitkeep
  src/app/routes/boards/.gitkeep
  src/app/routes/login/.gitkeep
  src/app/routes/myhistory/.gitkeep
  src/app/routes/mypage/.gitkeep
  src/app/routes/signup/.gitkeep
  src/app/stores/.gitkeep
  src/app/styles/.gitkeep
  src/app/types/.gitkeep
  src/app/utils/.gitkeep
Labels: documentation

#13 Fix: Lint 버그 수정 및 누락 패키지 설치
  .prettierrc
  package-lock.json
  package.json
Labels: ⚙️ 세팅, 🐛 버그, 📦 패키지

#23 반응형 태블릿 사이즈 추가
  tailwind.config.ts
Labels: 💄 스타일

#20 #17 공통컴포넌트 modal
  .eslintrc.json
  src/app/(component)/modal/page.tsx
  src/app/components/common/modal/Modal.tsx
  src/app/components/icons/IconClose.tsx
  src/app/hooks/useModal.ts
Labels: 📁 컴포넌트, 🔄 커스텀 훅

#24 폰트관련 수정완료
  src/app/layout.tsx
  src/app/styles/globals.css
  tailwind.config.ts
Labels: ⚙️ 세팅, 🐛 버그

#22 #11 공통컴포넌트 input
  package-lock.json
  package.json
  public/icons/.gitkeep
  public/icons/ic_invisibility.svg
  public/icons/ic_visibility.svg
  src/app/(routes)/addteam/.gitkeep
  src/app/(routes)/boards/.gitkeep
  src/app/(routes)/login/.gitkeep
  src/app/(routes)/myhistory/.gitkeep
  src/app/(routes)/mypage/.gitkeep
  src/app/(routes)/signup/.gitkeep
  src/app/components/common/input/auth/AuthInput.tsx
  src/app/components/icons/IconInVisibility.tsx
  src/app/components/icons/IconVisibility.tsx
  tsconfig.json
Labels: 📁 컴포넌트

#25 상단 네비게이션 부분 퍼블리싱 완료
  next.config.ts
  public/logos/.gitkeep
  public/logos/HeaderLogo.png
  src/app/components/.gitkeep
  src/app/components/common/Header/Boards.tsx
  src/app/components/common/Header/Header.tsx
  src/app/components/common/Header/SideMenubar.tsx
  src/app/components/icons/DropDownArrow.tsx
  src/app/components/icons/HeaderMenuBar.tsx
  src/app/components/icons/HeaderUserIcon.tsx
  src/app/layout.tsx
Labels: ✨ 신규 기능, 💬 논의 필요, 📁 컴포넌트

#33 text 컬러관련 수정완료
  tailwind.config.ts
Labels: 🐛 버그, 💄 스타일

#32 eslint 오류 해결
  .eslintrc.json
  package-lock.json
  src/app/components/common/input/auth/AuthInput.tsx
Labels: 🐛 버그

#34 Header 부분 코드리뷰, 회의내용 반영
  src/app/components/common/header/Boards.tsx
  src/app/components/common/header/Header.tsx
  src/app/components/common/header/SideMenubar.tsx
  src/app/layout.tsx
Labels: 🐛 버그, 📁 컴포넌트

#36 #35 axios setting
  package-lock.json
  package.json
  src/app/lib/instance.ts
Labels: 📡 API, 📦 패키지

#38 style: tailwind css intelliSense 적용
  src/app/components/common/modal/Modal.tsx
Labels: 💄 스타일, 💫 업데이트

#39 rename: 공통 input 이름, 경로 수정
  src/app/components/common/input/Input.tsx
Labels: 💫 업데이트, 📁 컴포넌트, 📝 문서

#40 회원가입 페이지 퍼블리싱완료, signup api연동완료
  package-lock.json
  package.json
  public/icons/google.png
  public/icons/kakao.png
  src/app/(routes)/signup/.gitkeep
  src/app/(routes)/signup/page.tsx
  src/app/components/signup/SignUpForm.tsx
  src/app/hooks/.gitkeep
  src/app/hooks/useSignUp.ts
  src/app/layout.tsx
  src/app/lib/auth/postSignUpApi.ts
  src/app/providers/TanStackProvider.tsx
  src/app/types/.gitkeep
  src/app/types/AuthType.ts
Labels: 📁 컴포넌트, 📦 패키지, 🔄 커스텀 훅

#44 #31 task list/api
  package-lock.json
  src/app/lib/comment/deleteComment.ts
  src/app/lib/comment/getComment.ts
  src/app/lib/comment/patchComment.ts
  src/app/lib/comment/postComment.ts
  src/app/lib/task/deleteTask.ts
  src/app/lib/task/getTask.ts
  src/app/lib/task/patchTask.ts
  src/app/lib/task/postRecurringTask.ts
  src/app/lib/task/postTask.ts
  src/app/lib/tasklist/deleteTaskList.ts
  src/app/lib/tasklist/getTaskList.ts
  src/app/lib/tasklist/patchTaskList.ts
  src/app/lib/tasklist/postTaskList.ts
  src/app/types/task.ts
Labels: 📡 API

#42 #28 팀 생성 페이지 퍼블리싱 및 API 연동
  src/app/addteam/page.tsx
  src/app/components/addteam/ProfileUploader.tsx
  src/app/components/addteam/TeamForm.tsx
  src/app/components/icons/IconProfile.tsx
  src/app/components/icons/IconProfileEdit.tsx
  src/app/lib/group/postGroup.ts
  src/app/lib/image/postImage.ts
Labels: ✨ 신규 기능, 💄 스타일, 📡 API

#48 #30 accessToken 관련 코드 주석처리
  src/app/lib/instance.ts
Labels: 📡 API

#49 오타 수정 및 모듈 설치 문제 해결
  package-lock.json
  public/contents/landing-section1.png
  src/app/components/landing/LandingFeatures.tsx
  src/app/page.tsx
Labels: 🐛 버그

#51 배포 에러 수정 : response 타입 명시
  src/app/lib/group/postGroup.ts
  src/app/lib/image/postImage.ts
Labels: 🐛 버그, ♻️ 리팩토링

#52 fix: response 구조 변경
  src/app/addteam/page.tsx
  src/app/lib/group/postGroup.ts
  src/app/lib/image/postImage.ts
Labels: 🐛 버그

#54 fix: 타입 명시화
  src/app/lib/task/getTask.ts
  src/app/lib/tasklist/getTaskList.ts
  src/app/lib/tasklist/patchTaskList.ts
  src/app/lib/tasklist/postTaskList.ts
Labels: 🐛 버그

#57 move: addteam dir 경로 수정
  src/app/(routes)/addteam/page.tsx
Labels: 📝 문서

#55 로그인 퍼블리싱완료, 리덕스 사용하여 전역상태관리 구현완료
  .eslintrc.json
  package-lock.json
  package.json
  src/app/(routes)/login/.gitkeep
  src/app/(routes)/login/page.tsx
  src/app/components/login/LoginForm.tsx
  src/app/hooks/useSignIn.ts
  src/app/layout.tsx
  src/app/lib/auth/postSignInApi.ts
  src/app/lib/instance.ts
  src/app/providers/ReduxProvider.tsx
  src/app/stores/.gitkeep
  src/app/stores/auth/authSlice.ts
  src/app/stores/store.ts
  src/app/types/AuthType.ts
Labels: 📁 컴포넌트, 📡 API, 📦 패키지, 🔄 커스텀 훅

#56 #31 task list/taskcard
  src/app/(component)/tasklist/page.tsx
  src/app/components/common/dropdown/DropdownItem.tsx
  src/app/components/common/dropdown/DropdownList.tsx
  src/app/components/icons/IconComment.tsx
  src/app/components/icons/IconRepeat.tsx
  src/app/components/icons/IconUncheckBox.tsx
  src/app/components/icons/TaskCardCalendar.tsx
  src/app/components/icons/TaskCardDropdown.tsx
  src/app/components/icons/VerticalBar.tsx
  src/app/components/tasklist/DatePicker.tsx
  src/app/components/tasklist/DateRepeatInfo.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/tasklist/TaskCardDropdown.tsx
  src/app/components/tasklist/TaskCardList.tsx
  src/app/lib/task/getTask.ts
  src/app/types/task.ts
  tailwind.config.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API

#59 fix: datePicker 빌드 오류 수정
  src/app/(component)/datepicker/page.tsx
Labels: 🐛 버그

#60 비밀번호 재설정하는 모달추가완료, 페이지 완성완료, api연동완료
  src/app/(routes)/reset-password/page.tsx
  src/app/components/common/button/Button.tsx
  src/app/components/login/LoginForm.tsx
  src/app/components/login/ResetPasswordModal.tsx
  src/app/components/resetpassword/ResetPasswordForm.tsx
  src/app/hooks/useConfirmPassword.ts
  src/app/hooks/useResetPassword.ts
  src/app/lib/instance.ts
  src/app/lib/user/patchResetPasswordApi.ts
  src/app/lib/user/postResetPasswordApi.ts
  src/app/providers/ReduxProvider.tsx
  src/app/stores/store.ts
  src/app/types/AuthType.ts
Labels: 🐛 버그, 📁 컴포넌트, 📡 API, 🔄 커스텀 훅

#62 fix: response 수정
  src/app/(routes)/[teamid]/edit/page.tsx
Labels: 🐛 버그

#65 #31 task list/task modal
  package-lock.json
  package.json
  src/app/(component)/tasklist/page.tsx
  src/app/components/common/dropdown/DropdownItem.tsx
  src/app/components/common/input/Input.tsx
  src/app/components/tasklist/CreateTaskModal.tsx
  src/app/components/tasklist/CustomCalendar.tsx
  src/app/components/tasklist/DateTimeSeletor.tsx
  src/app/components/tasklist/RepeatSelector.tsx
  src/app/components/tasklist/TaskCardDropdown.tsx
  src/app/components/tasklist/TimeSelector.tsx
  src/app/constants/dateConstants.ts
  src/app/lib/task/postRecurringTask.ts
  src/app/styles/globals.css
  src/app/types/task.ts
  src/app/utils/formValidation.ts
  src/app/utils/formatTime.ts
  tailwind.config.ts
Labels: ✨ 신규 기능, 📡 API, ♻️ 리팩토링, 📦 패키지

#63 #47 mypage 비밀번호 변경 제외 구현 완료
  package-lock.json
  package.json
  src/app/(component)/button/page.tsx
  src/app/(routes)/mypage/.gitkeep
  src/app/(routes)/mypage/page.tsx
  src/app/components/common/button/Button.tsx
  src/app/components/common/input/Input.tsx
  src/app/components/icons/IconAlert.tsx
  src/app/components/icons/IconMyProfile.tsx
  src/app/components/icons/IconSubtract.tsx
  src/app/components/mypage/DeleteAccount.tsx
  src/app/components/mypage/ProflieChanger.tsx
  src/app/components/mypage/ResetPassword.tsx
  src/app/lib/user/deleteUser.ts
  src/app/lib/user/getUser.ts
  src/app/lib/user/patchPassword.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API

#66 #45 멤버 관련 기능 퍼블리싱 및 API 연동
  src/app/(routes)/[teamid]/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/icons/IconProfileEmpty.tsx
  src/app/components/team/AddMemberModal.tsx
  src/app/components/team/DetailMemberModal.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/MemberContainer.tsx
  src/app/lib/group/deleteMemeber.ts
  src/app/lib/group/getGroup.ts
  src/app/lib/group/getInvitaion.ts
  src/app/lib/group/postAcceptInvitation.ts
  src/app/utils/copyWithExecCommand.ts
Labels: ✨ 신규 기능, 💄 스타일, 📁 컴포넌트, 📡 API, 🔨유틸리티

#68 할 일 수정/삭제 모달 UI 및 기능 구현
  package-lock.json
  package.json
  src/app/(component)/tasklist/page.tsx
  src/app/(routes)/[teamid]/tasklist/page.tsx
  src/app/components/common/button/Button.tsx
  src/app/components/common/dropdown/DropdownList.tsx
  src/app/components/icons/IconCheckBox.tsx
  src/app/components/icons/IconUncheckBox.tsx
  src/app/components/icons/TaskCardDropdown.tsx
  src/app/components/tasklist/CreateListModal.tsx
  src/app/components/tasklist/DatePicker.tsx
  src/app/components/tasklist/DeleteRecurringModal.tsx
  src/app/components/tasklist/DeleteTaskModal.tsx
  src/app/components/tasklist/EditTaskModal.tsx
  src/app/components/tasklist/TaskCard.tsx
  src/app/components/tasklist/TaskCardDropdown.tsx
  src/app/components/tasklist/TaskCardList.tsx
  src/app/layout.tsx
  src/app/lib/task/deleteTask.ts
  src/app/lib/task/patchTask.ts
  src/app/lib/tasklist/postTaskList.ts
  src/app/providers/ReduxProvider.tsx
  src/app/stores/hooks.ts
  src/app/stores/selectors.ts
  src/app/stores/tasksSlice.ts
  src/app/stores/tasksStore.ts
  src/app/types/task.ts
Labels: ✨ 신규 기능, 💄 스타일, 📡 API, 📦 패키지

#67 간편로그인 퍼블리싱 완료, 간편로그인 api연동(error)
  package-lock.json
  src/app/(routes)/auth/callback/google/page.tsx
  src/app/(routes)/auth/callback/kakao/page.tsx
  src/app/components/auth/callback/GoogleCallback.tsx
  src/app/components/auth/callback/KaKaoCallback.tsx
  src/app/components/login/LoginForm.tsx
  src/app/components/login/QuickLogin.tsx
  src/app/components/signup/SignUpForm.tsx
  src/app/hooks/useConfirmPassword.ts
  src/app/hooks/useResetPassword.ts
  src/app/hooks/useSignIn.ts
  src/app/hooks/useSignUp.ts
  src/app/lib/auth/postProviderApi.ts
  src/app/lib/auth/postRefreshApi.ts
  src/app/lib/auth/postSignInApi.ts
  src/app/lib/auth/postSignUpApi.ts
  src/app/lib/tokenInterceptor.ts
  src/app/lib/user/patchResetPasswordApi.ts
  src/app/lib/user/postResetPasswordApi.ts
  src/app/stores/auth/authSlice.ts
  src/app/utils/.gitkeep
  src/app/utils/handleTokenRefresh.ts
Labels: 🐛 버그, 💬 논의 필요, 📁 컴포넌트, 📡 API, ♻️ 리팩토링, 🔨유틸리티

#73 로그인, 회원가입 기능구현완료 (간편로그인아직해결X)
  .eslintrc.json
  package-lock.json
  package.json
  public/icons/google.png
  public/icons/kakao.png
  src/app/(routes)/auth/callback/google/page.tsx
  src/app/(routes)/auth/callback/kakao/page.tsx
  src/app/(routes)/login/.gitkeep
  src/app/(routes)/login/page.tsx
  src/app/(routes)/reset-password/page.tsx
  src/app/(routes)/signup/.gitkeep
  src/app/(routes)/signup/page.tsx
  src/app/components/auth/callback/GoogleCallback.tsx
  src/app/components/auth/callback/KaKaoCallback.tsx
  src/app/components/login/LoginForm.tsx
  src/app/components/login/QuickLogin.tsx
  src/app/components/login/ResetPasswordModal.tsx
  src/app/components/resetpassword/ResetPasswordForm.tsx
  src/app/components/signup/SignUpForm.tsx
  src/app/hooks/.gitkeep
  src/app/hooks/useConfirmPassword.ts
  src/app/hooks/useResetPassword.ts
  src/app/hooks/useSignIn.ts
  src/app/hooks/useSignUp.ts
  src/app/layout.tsx
  src/app/lib/auth/postProviderApi.ts
  src/app/lib/auth/postRefreshApi.ts
  src/app/lib/auth/postSignInApi.ts
  src/app/lib/auth/postSignUpApi.ts
  src/app/lib/instance.ts
  src/app/lib/oauth/postOauthApi.ts
  src/app/lib/tokenInterceptor.ts
  src/app/lib/user/patchResetPasswordApi.ts
  src/app/lib/user/postResetPasswordApi.ts
  src/app/providers/ReduxProvider.tsx
  src/app/stores/.gitkeep
  src/app/stores/auth/authSlice.ts
  src/app/stores/store.ts
  src/app/types/.gitkeep
  src/app/types/AuthType.ts
  src/app/utils/.gitkeep
  src/app/utils/handleTokenRefresh.ts
Labels: 💫 업데이트

#70 팀 페이지 할 일 목록 리스트 구현하기
  package-lock.json
  package.json
  src/app/(routes)/[teamid]/page.tsx
  src/app/(routes)/invitation/page.tsx
  src/app/components/icons/IconGear.tsx
  src/app/components/icons/IconProfileEmpty.tsx
  src/app/components/icons/IconTaskDone.tsx
  src/app/components/icons/TaskCardDropdown.tsx
  src/app/components/icons/TeamThumbnail.tsx
  src/app/components/team/AddMemberModal.tsx
  src/app/components/team/DetailMemberModal.tsx
  src/app/components/team/DropdownMenu.tsx
  src/app/components/team/MemberCard.tsx
  src/app/components/team/MemberContainer.tsx
  src/app/components/team/TeamHeader.tsx
  src/app/components/team/TodoList.tsx
  src/app/lib/group/deleteMemeber.ts
  src/app/lib/group/getGroup.ts
  src/app/lib/group/getInvitaion.ts
  src/app/lib/group/getTaskList.ts
  src/app/lib/group/postAcceptInvitation.ts
  src/app/lib/instance.ts
  src/app/utils/copyWithExecCommand.ts
  tailwind.config.ts
Labels: ✨ 신규 기능, 📁 컴포넌트, 📡 API
